Adding configuration for Syncthing
caddyserver/examples pull request #159
Opened 2019-08-10 18:22 UTC by theryecatcher

2019-08-10 18:32 UTC, mholt approved these changes
LGTM. Can you explain why you proxy only requests to `/syncthing` but then remove `/syncthing`? Maybe that should be explained in the readme, in case users want to proxy the whole site to syncthing?

2019-08-11 02:05 UTC, theryecatcher commented
I am exactly not sure, maybe you could help me here. This is what I tried and found out. This option isn't required while using Apache or Nginx. Something related to the way Caddy processes proxy requests. While invoking Caddy to reverse proxy a subdirectory to Syncthing like http://example.com/syncthing, it by default proxies requests to http://localhost:8384/syncthing which returns 404 which generally should have been proxied to http://localhost:8384. So that's the reason I had to include the `without /syncthing` directive. This is not the issue if you use `syncthing.example.com` as then it lives under it's own domain.

2019-08-11 03:19 UTC, mholt commented
@theryecatcher I'm not sure I follow as to what the problem is.

For a configuration such as:

```
proxy /foo localhost:8384/foo
```

Then a request to `example.com/foo` will proxy to `localhost:8384/foo`.  Similarly, a request to `example.com/foo/bar` will proxy to `localhost:8384/foo/bar`.

Is that not how nginx works?

If the backend (Syncthing) returns 404 at `/syncthing`, then maybe you should just remove the `/syncthing` parameter entirely:

```
proxy / localhost:8384
```

2019-08-15 00:56 UTC, theryecatcher commented
Thanks on the explanation. But my point was when you have a config option like `proxy /foo localhost:8384` the proxy gets redirected to `localhost:8384/foo` instead of `localhost:8384` which is what I was expecting, in case of sub folders under a domain. The example you stated works fine as that would be the root of the server which in the above case isn't. Maybe, I am missing something but please feel free to correct me if so.

2019-08-15 02:22 UTC, mholt commented
I think you're conflating two different things: request matching and reverse proxying. The request matcher does not mutate the request; i.e. it does not strip `/foo` from the request. It simply proxies requests with`/foo...` to the backend you specify.

So, you could remove the `/syncthing` path and just have requests without `/syncthing` and then you don't need `without /syncthing`. But if you intend that all requests to syncthing start with `/syncthing`, then you'll need to leave it. Does that make sense?

2019-08-16 04:46 UTC, whitestrake commented
> the proxy gets redirected

FYI, this term (redirected) has a specific meaning which doesn't apply here. What we're doing is _translating_ the request as it passes through the proxy layer (Caddy).

Normal function of a proxy is to pass the request upstream faithfully (including the whole URI requested by the client), and to return the result faithfully.

If you want your users to request `/syncthing/foo`, but you need the upstream server to receive a request for just `/foo`, this is where the translation must happen, and this is what `without` achieves in this case.

Note that this doesn't work very well for the majority of apps. You'll notice that without a trailing slash, this breaks the site heavily (hence the redirect you've added in the example). This "subfolder problem" occurs when the upstream app issues a link (such as to a CSS/JS/image asset) without understanding of the context (i.e. the omitted subfolder). Luckily the Syncthing devs appear to have written their links as relative, meaning they rely on what the _browser_ sees in order to determine what request to make - so it functions fine, but _only_ if there's a trailing slash.

Other web servers may do some of this translation automatically, without your configuration, I'm not sure.

2019-08-16 04:54 UTC, whitestrake requested changes

2019-08-16 04:54 UTC, whitestrake commented on syncthing/Caddyfile
> +	# redirect all requests (include trailing '/')
It might be more accurate for this comment to state that it "ensures all requests include trailing slashes".

2019-08-16 04:54 UTC, whitestrake commented on syncthing/Caddyfile
> +        proxy /syncthing 127.0.0.1:8384/ {
The hostname `127.0.0.1:8384` does not require a trailing slash.

2019-08-16 04:54 UTC, whitestrake commented on syncthing/Caddyfile
> +        redir /syncthing /syncthing/ 302
This redirection should be permanent. The site is broken (missing styling and other assets) without it. Remove the 302 here (implicit 301) or change it to an explicit 301.

2019-08-16 04:54 UTC, whitestrake commented on syncthing/Caddyfile
> +        timeouts {
Are these timeouts required? These will affect _all_ sites on the listener (probably the user's entire server).

2020-05-18 02:07 UTC, mholt commented
Thank you for your contribution. [Caddy 2 has been released](https://caddyserver.com/v2), so Caddy 1 is obsolete. We're deprecating this repository in favor of the [wiki category on our community forums](https://caddy.community/c/wiki/13), which accepts content for v2 and newer. The wiki does not require review, and anyone can edit your listing in the future. It will also be more visible and searchable.

Please upgrade to v2, and if your contribution is still relevant with v2 and our wiki does not yet cover your topic, consider contributing with the rest of our community to the new wiki. Thanks!

2020-05-18 02:07 UTC, closed without merging